CREATE DATABASE IF NOT EXISTS pfk_database CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE USER IF NOT EXISTS 'pfk_user'@'%' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON pfk_database.* TO 'pfk_user'@'%' WITH GRANT OPTION;
